// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVTWGELQQDxkUghnopi10TvmpPN7tGjw',
    appId: '1:185673637485:web:635c3b832af074bb35e964',
    messagingSenderId: '185673637485',
    projectId: 'fo0ds-4a2fb',
    authDomain: 'fo0ds-4a2fb.firebaseapp.com',
    databaseURL: 'https://fo0ds-4a2fb-default-rtdb.firebaseio.com',
    storageBucket: 'fo0ds-4a2fb.appspot.com',
    measurementId: 'G-HXY8EYPK4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdzCDSEFy6HfIgQSXajXfyhyWqQ4SAIQ',
    appId: '1:185673637485:android:7c4ebd54b58ae61735e964',
    messagingSenderId: '185673637485',
    projectId: 'fo0ds-4a2fb',
    databaseURL: 'https://fo0ds-4a2fb-default-rtdb.firebaseio.com',
    storageBucket: 'fo0ds-4a2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs13fXBrkCuPdQ6Hu7l4Rvs-ZTnc5qP1E',
    appId: '1:185673637485:ios:e88e3db7d53abc6c35e964',
    messagingSenderId: '185673637485',
    projectId: 'fo0ds-4a2fb',
    databaseURL: 'https://fo0ds-4a2fb-default-rtdb.firebaseio.com',
    storageBucket: 'fo0ds-4a2fb.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs13fXBrkCuPdQ6Hu7l4Rvs-ZTnc5qP1E',
    appId: '1:185673637485:ios:e88e3db7d53abc6c35e964',
    messagingSenderId: '185673637485',
    projectId: 'fo0ds-4a2fb',
    databaseURL: 'https://fo0ds-4a2fb-default-rtdb.firebaseio.com',
    storageBucket: 'fo0ds-4a2fb.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVTWGELQQDxkUghnopi10TvmpPN7tGjw',
    appId: '1:185673637485:web:a4bc1c788c47068d35e964',
    messagingSenderId: '185673637485',
    projectId: 'fo0ds-4a2fb',
    authDomain: 'fo0ds-4a2fb.firebaseapp.com',
    databaseURL: 'https://fo0ds-4a2fb-default-rtdb.firebaseio.com',
    storageBucket: 'fo0ds-4a2fb.appspot.com',
    measurementId: 'G-Q60QCK774R',
  );

}